# Generated by Django 5.0.6 on 2025-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar Chart"),
                    ("line", "Line Chart"),
                    ("pie", "Pie Chart"),
                ],
                default="bar",
                max_length=10,
            ),
        ),
    ]
