# Generated by Django 5.0.6 on 2025-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_question_chart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="visited",
            field=models.IntegerField(default=0),
        ),
    ]
